### ISSUE TITLE
Settings

### ISSUE THREAD

**Issue by Bollemii** [Bollemii/InventoryApp#5]
Settings :
- [x] Choose between list and cards view **=> blocked by #2 and #1**
- [x] Set the reminders time **=> blocked by #4**
- [x] Background color **=> blocked by #8**
